# Generated by Django 4.1.1 on 2022-09-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asgard',
            new_name='Item',
        ),
    ]
