# Generated by Django 4.1.1 on 2022-09-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0003_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
