# Generated by Django 4.1.1 on 2022-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0005_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
